title: Startupz
email: argikartika@gmail.com
description: >
  Startupz is a startup studio that develops and launches new companies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dashing-macaron-2898dd.netlify.app/" # the base hostname & protocol for your site
github_username: artikandri
plugins:
  - jekyll/vite

# Build settings
markdown: kramdown
source: src
destination: public
