email: argikartika@gmail.com
title: Startupz - We create Startupz.
description: >
  Startupz is a startup studio that develops and launches new companies.
baseurl: "/"
url: "https://dashing-macaron-2898dd.netlify.app/"
github_username: artikandri
plugins:
  - jekyll/vite
  - jekyll-seo-tag
permalink: /404.html
# Build settings
markdown: kramdown
source: src
destination: public
